import { FlagQuestion } from "../question";

export const flags : FlagQuestion[] = [
    new FlagQuestion(1, 'Andorra', 'AD'),
    new FlagQuestion(2, 'Abania', 'AL'),
    new FlagQuestion(3, 'Austria', 'AT'),
    new FlagQuestion(4, 'Bosnia and Herzegovina', 'BA'),
    new FlagQuestion(5, 'Belgium', 'BE'),
    new FlagQuestion(6, 'Bulgaria', 'BG'),
    new FlagQuestion(7, 'Belarus', 'BY'),
    new FlagQuestion(8, 'Switzerland', 'CH'),
    new FlagQuestion(9, 'Czech Republic', 'CZ'),
    new FlagQuestion(10, 'Germany', 'DE'),
    new FlagQuestion(11, 'Denmark', 'DK'),
    new FlagQuestion(12, 'Estonia', 'EE'),
    new FlagQuestion(13, 'Spain', 'ES'),
    new FlagQuestion(14, 'Finland', 'FI'),
    new FlagQuestion(15, 'France', 'FR'),
    new FlagQuestion(16, 'United Kingdom', 'GB'),
    new FlagQuestion(17, 'Georgia', 'GE'),
    new FlagQuestion(18, 'Greece', 'GR'),
    new FlagQuestion(19, 'Croatia', 'HR'),
    new FlagQuestion(20, 'Ireland', 'IE'),
    new FlagQuestion(21, 'Iceland', 'IS'),
    new FlagQuestion(22, 'Italy', 'IT'),
    new FlagQuestion(23, 'Liechtenstein', 'LI'),
    new FlagQuestion(24, 'Lithuania', 'LT'),
    new FlagQuestion(25, 'Luxembourg', 'LU'),
    new FlagQuestion(26, 'Latvia', 'LV'),
    new FlagQuestion(27, 'Monaco', 'MC'),
    new FlagQuestion(28, 'Moldova', 'MD'),
    new FlagQuestion(29, 'Montenegro', 'ME'),
    new FlagQuestion(30, 'Malta', 'MT'),
    new FlagQuestion(31, 'Netherlands', 'NL'),
    new FlagQuestion(32, 'Norway', 'NO'),
    new FlagQuestion(33, 'Poland', 'PL'),
    new FlagQuestion(34, 'Portugal', 'PT'),
    new FlagQuestion(35, 'Romania', 'RO'),
    new FlagQuestion(36, 'Serbia', 'RS'),
    new FlagQuestion(37, 'Russia', 'RU'),
    new FlagQuestion(38, 'Slovenia', 'SI'),
    new FlagQuestion(39, 'Slovakia', 'SK'),
    new FlagQuestion(40, 'San Marino', 'SM'),
    new FlagQuestion(41, 'Ukraine', 'UA'),
    new FlagQuestion(42, 'Vatican City', 'VA'),

    new FlagQuestion(43, 'United Arab Emirates', 'AE'),
    new FlagQuestion(44, 'China', 'CN'),
    new FlagQuestion(45, 'India', 'IN'),
    new FlagQuestion(46, 'Iraq', 'IQ'),
    new FlagQuestion(47, 'Japan', 'JP'),
    new FlagQuestion(48, "Democratic People's Republic of Korea (North Korea)", 'KP'),
    new FlagQuestion(49, 'Republic of Korea (South Korea)', 'KR'),
    new FlagQuestion(50, 'Kazakhstan', 'KZ'),
    new FlagQuestion(51, 'Mongolia', 'MN'),
    new FlagQuestion(52, 'Nepal', 'NP'),
    new FlagQuestion(53, 'Thailand', 'TH'),
    new FlagQuestion(54, 'Turkey', 'TR'),
    new FlagQuestion(55, 'Vietnam', 'VN'),

    new FlagQuestion(56, 'Argentina', 'AR'),
    new FlagQuestion(57, 'Armenia', 'AM'),
    new FlagQuestion(58, 'Brazil', 'BR'),
    new FlagQuestion(59, 'Canada', 'CA'),
    new FlagQuestion(60, 'Chile', 'CL'),
    new FlagQuestion(61, 'Colombia', 'CO'),
    new FlagQuestion(62, 'Cuba', 'CU'),
    new FlagQuestion(63, 'Jamaica', 'JM'),
    new FlagQuestion(64, 'Mexico', 'MX'),
    new FlagQuestion(65, 'Peru', 'PE'),
    new FlagQuestion(66, 'Unites States', 'US'),

    new FlagQuestion(67, 'Australia', 'AU'),
    new FlagQuestion(68, 'New Zealand', 'NZ'),
]